### ISSUE TITLE
ant fails to extract neo4j-community-2.1.4-unix.tar

### ISSUE THREAD

**Issue by cheshirecatalyst** [jimwebber/neo4j-tutorial#33]
❯ ant
Buildfile: /Users/emris/src/seth/neo4j-tutorial/build.xml

-download.check:

-make.download.dirs:
    [mkdir] Created dir: /Users/emris/src/seth/neo4j-tutorial/downloads/neo4j
    [mkdir] Created dir: /Users/emris/src/seth/neo4j-tutorial/downloads/jars

-download.and.unzip.neo4j.windows:

-download.and.uncompress.neo4j.unix:
      [get] Getting: http://dist.neo4j.org/neo4j-community-2.1.4-unix.tar.gz
      [get] To: /Users/emris/src/seth/neo4j-tutorial/downloads/neo4j/neo4j-community-2.1.4-unix.tar.gz
   [gunzip] Expanding /Users/emris/src/seth/neo4j-tutorial/downloads/neo4j/neo4j-community-2.1.4-unix.tar.gz to /Users/emris/src/seth/neo4j-tutorial/downloads/neo4j/neo4j-community-2.1.4-unix.tar
    [untar] Expanding: /Users/emris/src/seth/neo4j-tutorial/downloads/neo4j/neo4j-community-2.1.4-unix.tar into /Users/emris/src/seth/neo4j-tutorial/downloads/neo4j

BUILD FAILED
/Users/emris/src/seth/neo4j-tutorial/build.xml:57: Error while expanding /Users/emris/src/seth/neo4j-tutorial/downloads/neo4j/neo4j-community-2.1.4-unix.tar
java.io.IOException: Error detected parsing the header
	at org.apache.tools.tar.TarInputStream.getNextEntry(TarInputStream.java:292)
	at org.apache.tools.ant.taskdefs.Untar.expandStream(Untar.java:165)
	at org.apache.tools.ant.taskdefs.Untar.expandFile(Untar.java:114)
	at org.apache.tools.ant.taskdefs.Expand.execute(Expand.java:132)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.lang.IllegalArgumentException: Invalid byte 32 at offset 7 in '       {NUL}' len=8
	at org.apache.tools.tar.TarUtils.parseOctal(TarUtils.java:134)
	at org.apache.tools.tar.TarUtils.parseOctalOrBinary(TarUtils.java:172)
	at org.apache.tools.tar.TarEntry.parseTarHeader(TarEntry.java:912)
	at org.apache.tools.tar.TarEntry.parseTarHeader(TarEntry.java:899)
	at org.apache.tools.tar.TarEntry.<init>(TarEntry.java:323)
	at org.apache.tools.tar.TarInputStream.getNextEntry(TarInputStream.java:290)
	... 19 more

Total time: 1 minute 2 seconds

**Comment by ikwattro** [comment]
This issue is related to a bug with the Compress lib in Ant 1.9.4, and they are not hurry to fix it apparently.

https://issues.apache.org/bugzilla/show_bug.cgi?id=56641

Solution is to downgrade to Ant 1.9.3, if you are on os x check this gist : https://gist.github.com/ikwattro/80e5b77efb237d947771

**Comment by cheshirecatalyst** [comment]
Thanks

**Comment by cyrilfr** [comment]
Was this bug fixed somewhere? I got this error with common-compress 1.12.
